name: Setup CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby-2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url upstream https://$token:x-oauth-basic@github.com/$owner/$repo.git
          git remote set-url origin https://$token:x-oauth-basic@github.com/$username/$repo.git

      - name: Build
        run: |
          bundle install
          rake publish